version: '3.8'

services:
  nest_api:
    container_name: nest_api
    image: nest_api_dev:1.0.0
    build:
      context: .
      target: development
    command: npm run start:dev
    ports:
      - ${PORT:-4000}:${PORT:-4000}
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
  nest_mongodb:
    container_name: ${DATABASE_HOST}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

networks:
  default:
    driver: bridge
